language: node_js
node_js:
  - "6.0"
sudo: false
cache:
  directories:
    - node_modules
before_install: cd Coursera/javascript
before_script:
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script: "make test"