baseURL = "https://siemiatj.github.io/algorithms"
languageCode = "en-us"
title = "Algorithms"

[params]
    author_name = "sasklacz"
    description = "A set of algorithms for solving different problems."
    author_url = "https://saskla.cz"
    project_url = "http://github.com/siemiatj/algorithms"
    github_project_name = "algorithms"
    github_user_name = "siemiatj"

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"
